from langchain_core.output_parsers import PydanticOutputParser
from pydantic import BaseModel, Field
from typing import List, Any, Union

class AgentResponse(BaseModel):
    """
    Strict schema definition for the final response returned by the SQL Agent.
    This guarantees the frontend receives a predictable JSON structure.
    """
    question: str = Field(description="The original user question.")
    generated_sql: str = Field(description="The optimized SQLite query generated by the AI.")
    result: Any = Field(description="The raw execution results from the database.")
    summary: str = Field(description="The Markdown Table containing the formatted data, followed by a human-friendly business explanation of the results.")
    status: str = Field(description="Status of the operation, e.g., 'success' or 'error'.")

# Instantiate the parser
# This parser can generate format instructions for the LLM and parse the final output
agent_response_parser = PydanticOutputParser(pydantic_object=AgentResponse)
